name: pockit
version: '0.1.5'
summary: Unofficial Pocket Client
description: Unofficial Pocket Client

grade: stable
confinement: strict

apps:
  pockit:
    command: desktop-launch $SNAP/bin/pockit
    plugs:
      - unity7
      - x11
      - opengl
      - gsettings
      - network
      - network-bind
      - pulseaudio
      - alsa
      - location-control
      - location-observe

parts:
  launcher:
    plugin: dump
    source: .
    organize:
        launcher.sh: bin/pockit
  pockit:
    plugin: qmake
    source: https://github.com/turanmahmudov/PockIt2.git
    qt-version: qt5
    build-packages:
    - ubuntu-sdk-libs
    - qtubuntu-desktop
    - qmlscene
    - qml-module-ubuntu-components
    - liboxideqt-qmlplugin
    - qml-module-oxide-ubuntu
    - qtdeclarative5-dev
    stage-packages:
    - ubuntu-sdk-libs
    - qtubuntu-desktop
    - qmlscene
    - qml-module-ubuntu-components
    - qtdeclarative5-dev
    - liboxideqt-qmlplugin
    - qml-module-oxide-ubuntu
    - gstreamer1.0-pulseaudio
    - gstreamer1.0-libav
    after: [desktop-qt5]
    organize:
      icon.png: meta/gui/pockit.png
